name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2' # Specify your required Python version

      - name: Build the Docker image
        run: docker build -f Dockerfile -t test .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: test
          format: 'json'
          output: trivy.json
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Run Python script to send metrics to Datadog
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          GITHUB_REPO: ${{ github.repository }}
        run: python send_metrics.py
